# Generated by Django 3.2.15 on 2022-09-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
