# Generated by Django 3.2.15 on 2022-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('counted_view', models.IntegerField()),
                ('status', models.BooleanField()),
                ('published_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
