# Generated by Django 3.2.15 on 2022-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
