# Generated by Django 3.2.15 on 2022-08-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
